### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by fafhrd91** [fafhrd91/mdl#2]
Let's post ideas what we want to see in this package

**Comment by fafhrd91** [comment]
@andriisoldatenko

@asvetlov would like to participate?

**Comment by cr0hn** [comment]
Hi!

It sound good, but I have to many in progress projects and currently I have not more time.

I hope the best for the project.

Best regards!

**Comment by fafhrd91** [comment]
some thoughts on middlewares

Middlewares represent work that needs to be done for every request. Examples are auth or session management, logging. Some of the problems with current design, requirements for middlewares are implicit. The Way how middleware injects data into current request is not standardized  (example auth injects user object) overall accessibility of middleware interfaces requirements is bad.

Middleware should register request parameters, response parameters with `mdl` layer. 
Also middleware can register parameter which it wants to inject into route parameters definition. Then `mdl` layer can modify swagger definition for each route and expose
through standard `params` object.

how to register middleware parameters is TBD.
also there is question how to expose location `header`, right now we use same schema as wsgi.

**Comment by fafhrd91** [comment]
i'd like to add support for py2.7 and flask.

**Comment by andriisoldatenko** [comment]
@fafhrd91 I think we should create docs and tutorial.
Also can we use ideas from https://github.com/cr0hn/aiohttp-swagger or not?

**Comment by fafhrd91** [comment]
We can use any ideas.

Docs and tutorial is up to you, I think it is a bit early

**Comment by fafhrd91** [comment]
I don't have interests in this package anymore. do we want to keep it in aio-libs?

@asvetlov ?

**Comment by asvetlov** [comment]
I don't want to support it, my spare time is very limited.
I even did not take a glaze on code source.
Would you move the project back to your personal account?

**Comment by fafhrd91** [comment]
yes, I will move it.
